### ISSUE TITLE
regex pattern or specific replacement

### ISSUE THREAD

**Issue by grommas** [fabianmichael/kirby-typography#20]
Hi Fabian, your adaption is pretty neat! Will there be a way to make further typographical corrections in your next version? like searching for regex patterns or speficic word combinations, then changing the whitespace to a smaller one and wrap the term to prevent line breaking etc?

**Comment by fabianmichael** [comment]
Hi @grommas,

the plugin is a port of wp Typography, which is a WordPress-plugin that has been around for a several years. Only recently, the author put the library behind that plugin into a separate rpository (https://github.com/mundschenk-at/php-typography), which should make future updates of my plugin much easier.

So development of new features basically depends on that library. I hope to find some time during this winter to develop a new version of my plugin that will use the latest version of PHP Typography and which aims to be compatible with Kirby 3 (Kirby Next), once it is released.
