### ISSUE TITLE
Error with Smartypants in Kirby 2.5.8

### ISSUE THREAD

**Issue by tristantbg** [fabianmichael/kirby-typography#22]
`Declaration of Kirby\Plugins\Typography\Component\Typography::parse($text, $force = false) should be compatible with Kirby\Component\Smartypants::parse($text, $force, Field $field)`

Any idea how to fix this ?

Thanks a lot

**Comment by paulrobertlloyd** [comment]
I’m seeing the same issue. I’m guessing it relates to this change:

> Custom Markdown and Smartypants parser components now have access to the `Field` object [#611](https://github.com/getkirby/kirby/pull/611)

**Comment by rcvd** [comment]
Facing it too. Here is how I fixed it:

Add this in line after use Kirby\Plugins\Typography\Cache;

`use Field;`

and change 

`public function parse($text, $force = false) {`

to 

`public function parse($text, $force = false, Field $field = NULL) {`

**Comment by wottpal** [comment]
Same Issue
