### ISSUE TITLE
Loads non-existent file in panel

### ISSUE THREAD

**Issue by chpio** [fabianmichael/kirby-typography#25]
This plugin loads a non existing file (also i couldn't find a htaccess with this path in it).

`http://127.0.0.1/plugins/typography/widget/api/status`

**Comment by fabianmichael** [comment]
The `.htaccess` redirects all requests to non-existant files to Kirby by default. Kirby then checks, whether a route exists that matches the requested file’s pattern. In this case, the Kirby-Typography makes a request to its own API for retrieving status information about the plugin’s cache.

Do other routes work have the the `.htaccess` files (in the root directoy and the panel subfolder) been setup correctly?

**Comment by chpio** [comment]
ahh, thank you. I think it's conflicting with our (poorly implemented) redirection script. After adding `plugins` as an exception i got a 404 error from kirby, but im stopping the "investigation" now bc it's a low priority thing.
