### ISSUE TITLE
Consider disabling by default: typography.hyphenation

### ISSUE THREAD

**Issue by fvsch** [fabianmichael/kirby-typography#6]
Feel free to close this issue if you disagree. :)

Rationale: while other things like typographically incorrect quotes and fake dashes (`--`) can be seen as defects or limitations of the source text that should probably be corrected whenever possible, hyphenation is a design choice that designers should probably opt in. Especially since it's very uncommon on the web.

**Comment by fabianmichael** [comment]
While I generally agree with your opinion that hyphenation is a design choice, I still think that this is one of the key features of both wp-Typography and Kirby-Typography. If you only need a few basic typographic enhancements, you’re IMHO better off with using SmartyPants, which is much faster than the PHP-Typography parser – though not that extensive. So I prefer to leave this setting enabled by default.

If you use a decent text editor, replacements like Smart Quotes can also be done before SmartyPants or PHP-Typography come into play. Same goes for dashes. If you’re on OS X, they’re easy to type anyway. With German keyboard Layout for example, you just have to hit <kbd>⌥</kbd><kbd>-</kbd> to get an EN dash and <kbd>⌥</kbd><kbd>⇧</kbd><kbd>-</kbd> to get an EM dash.

**Comment by fvsch** [comment]
Makes sense. :)
